package db;
// Generated 2017-03-13 21:42:21 by Hibernate Tools 4.3.1

/**
 * Highscore generated by hbm2java
 */
public class Highscore  implements java.io.Serializable {
    
    private Integer id;
    private String name;
    private Integer score;

    public Highscore() {
    }

    public Highscore(String name, Integer score) {
       this.name = name;
       this.score = score;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    public Integer getScore() {
        return this.score;
    }
    
    public void setScore(Integer score) {
        this.score = score;
    }
}


